[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lamb"
version = "1.0"
authors = [
    {name = "Gabriel Vitor Klaumann Gubert", email = "Gabriel.KlaumannGubert@thi.de"},
]
dependencies = [
    "langchain",
    "langchain_community",
    "langchain_openai",
    "langchain-text-splitters",
    "langgraph",
    "langgraph-checkpoint-sqlite",
    "litellm[proxy]",
    "markdownify",
    "numpy",
    "pydantic",
    "rich",
    "tiktoken",
    "toml",
    "tree-sitter",
    "tree-sitter-html",
    "tree_sitter_language_pack"
]

[project.scripts]
lamb = "lamb.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
lamb = ["languages.yaml"]