[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lamb"
version = "1.0"
authors = [
    {name = "Gabriel Vitor Klaumann Gubert", email = "Gabriel.KlaumannGubert@thi.de"},
]
dependencies = [
    "jupyter-ai",
    "jupyter-ai-magics",
    "toml",
    "langchain",
    "langchain_openai",
    "langgraph",
    "numpy",
    "tree_sitter_language_pack"
]

[project.scripts]
lamb = "lamb.cli:main"

[project.entry-points."jupyter_ai.model_providers"]
lamb = "lamb.jupyter.providers:LambProvider"

[tool.setuptools.packages.find]
where = ["src"]
